language: node_js
node_js:
- 8
- 10
install: true
before_deploy: "cd packages && tar -zcvf react-scripts-$TRAVIS_TAG.tgz react-scripts"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: N59INfaqnLplvWQdUEAd3BFJKsV8MN/5b513U/WpLGvKGRLdWlT3lJK5hchFnS85J40aXWlmin5cvG1eURLFxOKKGox5YV1y4I/4PnIqqscnU7HHcWgltqsVLVY3XVflp+tcKicSc+dqDT1wJigOEDGj9Kb5bGV61wbsKFB8R6QzoEd74jIgPjaf+eFXh6jharRJtn37J/qOKYwsDNbE5CZVCJu1Q9MZo5cXBXVtHvBzm1GboL0Efqc/ZvsWsZYptkqxJTTURPJQJ44cfoqmFHwX2gji0oSCjwO/t54lT7PL1LD88P9kMTTGtfmG1jH0mh6SyYlHWfP5eU1U/yrfFaRm+v70zFpB6uQXoQ2oVioN/nMcOnze4ZgAf3wnpaUs0jUBZLg+jjOKn6Za4C87WQ66nkq1ImSs9WP7DSzmlusqihh8OPTwpaqL5SsxUImPVAW9+f6VeN7o2IzJWor+Mdkvwgt4hCfFCZB2AdBpt5suieJUTxUhzAi+TgHm5ksBPME5nxomlL2mbihO935y+FCAhsCBcIUpIu6STqOpyvCCBkCXR/y5xxNDm2ZY3aM+pQ9XDArERuhT8uTXmZI+190NnqkafG6F0iCrQwVMISUOlA6i7iErMUWkj8EMqkfZJtARtNlrmM+mV5Ih4SPTRmF3lAjTbqc7amPKPqezvAc=
  file: packages/react-scripts-$TRAVIS_TAG.tgz
  on:
    repo: joeycozza/create-react-app
    tags: true
